SCALE = 0.5

# JET Player
JET_SCALE = 0.25
MAX_SPEED = 4
LIVES = 3

# Enemy
ENEMY_SPEED = 1
ENEMY_LIVES = 1
STARTING_ENEMIES_COUNT = 5

# Window
SCREEN_TITLE = "Jet Fighters - Alpha Version"
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

# Screen limits
OFFSCREEN_SPACE = 300
LEFT_LIMIT = -OFFSCREEN_SPACE
RIGHT_LIMIT = SCREEN_WIDTH + OFFSCREEN_SPACE
BOTTOM_LIMIT = -OFFSCREEN_SPACE
TOP_LIMIT = SCREEN_HEIGHT + OFFSCREEN_SPACE

# Clouds
CLOUD_SPEED = [1, 5]
CLOUD_SCALE = [0.25, 1]